[project]
name = "mybin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mylib",
]

[tool.uv.sources]
mylib = { path = "../mylib" }
